-- Convite de Casamento V2
-- Migração idempotente da estrutura estática/V1 para o modelo multi-evento da V2.
-- Execute no SQL Editor do Supabase antes de publicar a nova aplicação.

begin;

create extension if not exists pgcrypto;

create table if not exists public.eventos (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  nome_evento text not null,
  nome_casal text not null,
  data_evento date,
  horario_evento time,
  local_cerimonia text,
  link_maps_cerimonia text,
  local_recepcao text,
  link_maps_recepcao text,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.eventos (
  slug,
  nome_evento,
  nome_casal,
  data_evento,
  horario_evento,
  local_cerimonia,
  link_maps_cerimonia,
  local_recepcao,
  link_maps_recepcao,
  ativo
)
values (
  'flavio-ana-paula',
  'Casamento Flávio & Ana Paula',
  'Flávio & Ana Paula',
  date '2026-08-15',
  time '17:30',
  'Santuário de Nossa Senhora de Fátima, Rua da Garoupa, 01, Parque das Dunas IV, Pajuçara, Natal/RN',
  'https://www.google.com/maps/dir/?api=1&destination=Santu%C3%A1rio%20de%20Nossa%20Senhora%20de%20F%C3%A1tima%2C%20Rua%20da%20Garoupa%2C%2001%2C%20Parque%20das%20Dunas%20IV%2C%20Paju%C3%A7ara%2C%20Natal%2FRN',
  'Rua Tambaqui, nº 60, Natal/RN',
  'https://www.google.com/maps/dir/?api=1&destination=Rua%20Tambaqui%2C%20n%C2%BA%2060%2C%20Natal%2FRN',
  true
)
on conflict (slug) do update set
  nome_evento = excluded.nome_evento,
  nome_casal = excluded.nome_casal,
  data_evento = coalesce(public.eventos.data_evento, excluded.data_evento),
  horario_evento = coalesce(public.eventos.horario_evento, excluded.horario_evento),
  local_cerimonia = coalesce(nullif(public.eventos.local_cerimonia, ''), excluded.local_cerimonia),
  link_maps_cerimonia = case
    when public.eventos.link_maps_cerimonia is null
      or trim(public.eventos.link_maps_cerimonia) = ''
      or trim(trailing '/' from public.eventos.link_maps_cerimonia) in ('https://maps.google.com', 'https://www.google.com/maps')
    then excluded.link_maps_cerimonia
    else public.eventos.link_maps_cerimonia
  end,
  local_recepcao = coalesce(nullif(public.eventos.local_recepcao, ''), excluded.local_recepcao),
  link_maps_recepcao = case
    when public.eventos.link_maps_recepcao is null
      or trim(public.eventos.link_maps_recepcao) = ''
      or trim(trailing '/' from public.eventos.link_maps_recepcao) in ('https://maps.google.com', 'https://www.google.com/maps')
    then excluded.link_maps_recepcao
    else public.eventos.link_maps_recepcao
  end;

create table if not exists public.configuracoes_evento (
  id bigint generated by default as identity primary key,
  evento_id bigint not null unique references public.eventos(id) on delete cascade,
  mensagem_confirmacao text,
  data_limite_confirmacao date,
  chave_pix text,
  qr_pix_url text,
  dress_code_titulo text,
  dress_code_descricao text,
  dress_code_homens text,
  dress_code_mulheres text,
  dress_code_cores text,
  dress_code_cores_paleta jsonb not null default '[{"nome":"Azul-marinho","cor":"#08265E"},{"nome":"Bordô","cor":"#800000"},{"nome":"Verde","cor":"#3F6B4A"}]'::jsonb,
  dress_code_observacao text,
  max_acompanhantes integer not null default 4 check (max_acompanhantes between 0 and 10),
  cor_primaria text default '#800000',
  cor_secundaria text default '#08265e',
  cor_acento text default '#c9a227',
  cor_fundo text default '#fffaf8',
  cor_superficie text default '#ffffff',
  modelo_layout text not null default 'classic',
  hero_background_type text not null default 'image',
  hero_background_url text,
  hero_overlay_opacity integer not null default 45 check (hero_overlay_opacity between 0 and 90),
  historia_ativa boolean not null default true,
  historia_titulo text,
  historia_descricao text,
  historia_modelo_grid text not null default 'editorial',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Garante as colunas da V2 quando configuracoes_evento já existia parcialmente.
alter table public.configuracoes_evento add column if not exists evento_id bigint;
alter table public.configuracoes_evento add column if not exists mensagem_confirmacao text;
alter table public.configuracoes_evento add column if not exists data_limite_confirmacao date;
alter table public.configuracoes_evento add column if not exists chave_pix text;
alter table public.configuracoes_evento add column if not exists qr_pix_url text;
alter table public.configuracoes_evento add column if not exists dress_code_titulo text;
alter table public.configuracoes_evento add column if not exists dress_code_descricao text;
alter table public.configuracoes_evento add column if not exists dress_code_homens text;
alter table public.configuracoes_evento add column if not exists dress_code_mulheres text;
alter table public.configuracoes_evento add column if not exists dress_code_cores text;
alter table public.configuracoes_evento add column if not exists dress_code_cores_paleta jsonb default '[{"nome":"Azul-marinho","cor":"#08265E"},{"nome":"Bordô","cor":"#800000"},{"nome":"Verde","cor":"#3F6B4A"}]'::jsonb;
alter table public.configuracoes_evento add column if not exists dress_code_observacao text;
alter table public.configuracoes_evento add column if not exists max_acompanhantes integer default 4;
alter table public.configuracoes_evento add column if not exists cor_primaria text default '#800000';
alter table public.configuracoes_evento add column if not exists cor_secundaria text default '#08265e';
alter table public.configuracoes_evento add column if not exists cor_acento text default '#c9a227';
alter table public.configuracoes_evento add column if not exists cor_fundo text default '#fffaf8';
alter table public.configuracoes_evento add column if not exists cor_superficie text default '#ffffff';
alter table public.configuracoes_evento add column if not exists modelo_layout text default 'classic';
alter table public.configuracoes_evento add column if not exists hero_background_type text default 'image';
alter table public.configuracoes_evento add column if not exists hero_background_url text;
alter table public.configuracoes_evento add column if not exists hero_overlay_opacity integer default 45;
alter table public.configuracoes_evento add column if not exists historia_ativa boolean default true;
alter table public.configuracoes_evento add column if not exists historia_titulo text;
alter table public.configuracoes_evento add column if not exists historia_descricao text;
alter table public.configuracoes_evento add column if not exists historia_modelo_grid text default 'editorial';
alter table public.configuracoes_evento add column if not exists created_at timestamptz default now();
alter table public.configuracoes_evento add column if not exists updated_at timestamptz default now();
create unique index if not exists configuracoes_evento_evento_id_key on public.configuracoes_evento(evento_id);

insert into public.configuracoes_evento (
  evento_id,
  mensagem_confirmacao,
  data_limite_confirmacao,
  chave_pix,
  qr_pix_url,
  dress_code_titulo,
  dress_code_descricao,
  dress_code_homens,
  dress_code_mulheres,
  dress_code_cores,
  dress_code_cores_paleta,
  dress_code_observacao,
  max_acompanhantes,
  cor_primaria,
  cor_secundaria,
  cor_acento,
  cor_fundo,
  cor_superficie,
  modelo_layout,
  hero_background_type,
  hero_background_url,
  hero_overlay_opacity,
  historia_ativa,
  historia_titulo,
  historia_descricao,
  historia_modelo_grid
)
select
  id,
  'Confirmação enviada com sucesso. Obrigado! Nos vemos no nosso grande dia.',
  date '2026-07-31',
  '8667e1d3-582a-4d60-b387-57cc1cef1837',
  '/images/qr-pix.png',
  'Esporte fino',
  'Queremos todos elegantes e confortáveis para celebrar conosco.',
  'Camisa social; calça de sarja ou alfaiataria; sapato social ou mocassim; blazer opcional. Evitar bermuda, jeans e boné.',
  'Vestido longo ou midi; saia longa com blusa elegante; salto ou rasteira refinada. Evitar peças muito curtas e transparências excessivas.',
  'Evite vermelho bordô, azul marinho e verde.',
  '[{"nome":"Azul-marinho","cor":"#08265E"},{"nome":"Bordô","cor":"#800000"},{"nome":"Verde","cor":"#3F6B4A"}]'::jsonb,
  'As cores reservadas fazem parte da identidade visual do casamento.',
  4,
  '#800000',
  '#08265e',
  '#c9a227',
  '#fffaf8',
  '#ffffff',
  'classic',
  'image',
  '/images/casal-principal.jpg',
  45,
  true,
  'Nossa história',
  'Alguns momentos especiais que fazem parte da nossa caminhada até este grande dia.',
  'editorial'
from public.eventos
where slug = 'flavio-ana-paula'
on conflict (evento_id) do nothing;

-- Recupera configurações operacionais existentes da V1, quando a tabela estiver disponível.
do $$
declare
  v_evento_id bigint;
begin
  select id into v_evento_id from public.eventos where slug = 'flavio-ana-paula';

  if to_regclass('public.configuracoes_site') is not null then
    execute format(
      'update public.configuracoes_evento ce
       set mensagem_confirmacao = coalesce(cs.mensagem_confirmacao, ce.mensagem_confirmacao),
           data_limite_confirmacao = coalesce(cs.data_limite_confirmacao, ce.data_limite_confirmacao),
           updated_at = now()
       from public.configuracoes_site cs
       where ce.evento_id = %s and cs.id = 1',
      v_evento_id
    );
  end if;
end $$;

create table if not exists public.confirmacoes (
  id bigint generated by default as identity primary key,
  evento_id bigint references public.eventos(id) on delete cascade,
  nome text not null,
  telefone text,
  acompanhantes integer not null default 0,
  nomes_acompanhantes jsonb,
  presenca text not null,
  observacoes text,
  created_at timestamptz not null default now()
);
alter table public.confirmacoes add column if not exists evento_id bigint;
alter table public.confirmacoes add column if not exists telefone text;
alter table public.confirmacoes add column if not exists acompanhantes integer default 0;
alter table public.confirmacoes add column if not exists nomes_acompanhantes jsonb;
alter table public.confirmacoes add column if not exists observacoes text;
alter table public.confirmacoes add column if not exists created_at timestamptz default now();

create table if not exists public.presentes (
  id bigint generated by default as identity primary key,
  evento_id bigint references public.eventos(id) on delete cascade,
  nome text not null,
  valor text,
  descricao text,
  imagem_url text,
  usa_cotas boolean not null default false,
  quantidade_total integer not null default 1,
  quantidade_reservada integer not null default 0,
  status text not null default 'disponivel',
  created_at timestamptz not null default now()
);
alter table public.presentes add column if not exists evento_id bigint;
alter table public.presentes add column if not exists valor text;
alter table public.presentes add column if not exists descricao text;
alter table public.presentes add column if not exists imagem_url text;
alter table public.presentes add column if not exists usa_cotas boolean default false;
alter table public.presentes add column if not exists quantidade_total integer default 1;
alter table public.presentes add column if not exists quantidade_reservada integer default 0;
alter table public.presentes add column if not exists status text default 'disponivel';
alter table public.presentes add column if not exists created_at timestamptz default now();

create table if not exists public.reservas_presentes (
  id bigint generated by default as identity primary key,
  evento_id bigint references public.eventos(id) on delete cascade,
  presente_id bigint not null references public.presentes(id) on delete cascade,
  reservado_por text,
  created_at timestamptz not null default now()
);
alter table public.reservas_presentes add column if not exists evento_id bigint;
alter table public.reservas_presentes add column if not exists reservado_por text;
alter table public.reservas_presentes add column if not exists created_at timestamptz default now();

-- Copia o nome usado na V1 (nome_reserva) para o padrão da V2.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'reservas_presentes'
      and column_name = 'nome_reserva'
  ) then
    execute 'update public.reservas_presentes
             set reservado_por = coalesce(nullif(reservado_por, ''''), nome_reserva)
             where reservado_por is null or trim(reservado_por) = ''''';
  end if;
end $$;

create table if not exists public.galeria_evento (
  id bigint generated by default as identity primary key,
  evento_id bigint not null references public.eventos(id) on delete cascade,
  imagem_url text not null,
  ordem integer not null default 0,
  destaque boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.historia_momentos (
  id bigint generated by default as identity primary key,
  evento_id bigint not null references public.eventos(id) on delete cascade,
  imagem_url text not null,
  titulo text,
  descricao text,
  ordem integer not null default 0,
  destaque boolean not null default false,
  created_at timestamptz not null default now()
);

-- Vincula todo o conteúdo legado ao evento principal.
do $$
declare
  v_evento_id bigint;
begin
  select id into v_evento_id from public.eventos where slug = 'flavio-ana-paula';

  update public.confirmacoes set evento_id = v_evento_id where evento_id is null;
  update public.presentes set evento_id = v_evento_id where evento_id is null;
  update public.reservas_presentes rp
     set evento_id = coalesce(
       (select p.evento_id from public.presentes p where p.id = rp.presente_id),
       v_evento_id
     )
   where rp.evento_id is null;

  update public.reservas_presentes
     set reservado_por = 'Reserva migrada'
   where reservado_por is null or trim(reservado_por) = '';

  update public.presentes
     set usa_cotas = coalesce(usa_cotas, false),
         quantidade_total = greatest(coalesce(quantidade_total, 1), 1),
         quantidade_reservada = greatest(coalesce(quantidade_reservada, 0), 0),
         status = case
           when coalesce(usa_cotas, false)
             and coalesce(quantidade_reservada, 0) < greatest(coalesce(quantidade_total, 1), 1)
             then 'disponivel'
           when coalesce(quantidade_reservada, 0) > 0 then 'reservado'
           else coalesce(nullif(status, ''), 'disponivel')
         end;
end $$;

alter table public.confirmacoes alter column evento_id set not null;
alter table public.presentes alter column evento_id set not null;
alter table public.reservas_presentes alter column evento_id set not null;
alter table public.reservas_presentes alter column reservado_por set not null;

-- Adiciona as referências quando a tabela já existia na V1.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'configuracoes_evento_evento_id_fkey') then
    alter table public.configuracoes_evento
      add constraint configuracoes_evento_evento_id_fkey
      foreign key (evento_id) references public.eventos(id) on delete cascade;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'confirmacoes_evento_id_fkey') then
    alter table public.confirmacoes
      add constraint confirmacoes_evento_id_fkey
      foreign key (evento_id) references public.eventos(id) on delete cascade;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'presentes_evento_id_fkey') then
    alter table public.presentes
      add constraint presentes_evento_id_fkey
      foreign key (evento_id) references public.eventos(id) on delete cascade;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'reservas_presentes_evento_id_fkey') then
    alter table public.reservas_presentes
      add constraint reservas_presentes_evento_id_fkey
      foreign key (evento_id) references public.eventos(id) on delete cascade;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'reservas_presentes_presente_id_fkey') then
    alter table public.reservas_presentes
      add constraint reservas_presentes_presente_id_fkey
      foreign key (presente_id) references public.presentes(id) on delete cascade;
  end if;
end $$;

-- Seeds visuais equivalentes aos arquivos já usados na V1.
insert into public.galeria_evento (evento_id, imagem_url, ordem, destaque)
select e.id, seed.imagem_url, seed.ordem, seed.destaque
from public.eventos e
cross join (
  values
    ('/images/momento-1.jpg'::text, 1, true),
    ('/images/momento-2.jpg'::text, 2, false),
    ('/images/momento-3.jpg'::text, 3, false),
    ('/images/momento-4.jpg'::text, 4, false),
    ('/images/momento-5.jpg'::text, 5, false)
) as seed(imagem_url, ordem, destaque)
where e.slug = 'flavio-ana-paula'
  and not exists (
    select 1 from public.galeria_evento g where g.evento_id = e.id
  );

insert into public.historia_momentos (
  evento_id,
  imagem_url,
  titulo,
  descricao,
  ordem,
  destaque
)
select e.id, seed.imagem_url, seed.titulo, seed.descricao, seed.ordem, seed.destaque
from public.eventos e
cross join (
  values
    ('/images/casal-principal.jpg'::text, 'Um novo capítulo', 'Entre sonhos, oração e amor, estamos construindo o dia mais especial das nossas vidas.', 1, true),
    ('/images/momento-1.jpg'::text, 'Nossa caminhada', 'Registros de uma história construída com carinho, companheirismo e muitos planos.', 2, false),
    ('/images/casal-final.jpg'::text, 'Rumo ao grande dia', 'Agora contamos os dias para celebrar essa nova fase ao lado de quem amamos.', 3, false)
) as seed(imagem_url, titulo, descricao, ordem, destaque)
where e.slug = 'flavio-ana-paula'
  and not exists (
    select 1 from public.historia_momentos h where h.evento_id = e.id
  );

create index if not exists confirmacoes_evento_id_idx on public.confirmacoes(evento_id);
create index if not exists presentes_evento_id_idx on public.presentes(evento_id);
create index if not exists reservas_presentes_evento_id_idx on public.reservas_presentes(evento_id);
create index if not exists reservas_presentes_presente_id_idx on public.reservas_presentes(presente_id);
create index if not exists galeria_evento_evento_id_idx on public.galeria_evento(evento_id, ordem);
create index if not exists historia_momentos_evento_id_idx on public.historia_momentos(evento_id, ordem);

-- Reserva atômica: evita duas pessoas consumirem a última cota simultaneamente.
create or replace function public.reservar_presente(
  p_evento_id bigint,
  p_presente_id bigint,
  p_reservado_por text
)
returns table (
  presente_id bigint,
  quantidade_reservada integer,
  status text,
  usa_cotas boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_presente public.presentes%rowtype;
  v_nova_quantidade integer;
  v_novo_status text;
begin
  if trim(coalesce(p_reservado_por, '')) = '' then
    raise exception 'Informe seu nome para reservar.';
  end if;

  select *
    into v_presente
    from public.presentes p
   where p.id = p_presente_id
     and p.evento_id = p_evento_id
   for update;

  if not found then
    raise exception 'Presente não encontrado para este evento.';
  end if;

  if v_presente.usa_cotas then
    if v_presente.quantidade_reservada >= v_presente.quantidade_total then
      raise exception 'Todas as cotas deste presente já foram reservadas.';
    end if;
  elsif v_presente.status = 'reservado' or v_presente.quantidade_reservada > 0 then
    raise exception 'Este presente já foi reservado.';
  end if;

  insert into public.reservas_presentes (
    evento_id,
    presente_id,
    reservado_por
  ) values (
    p_evento_id,
    p_presente_id,
    left(trim(p_reservado_por), 120)
  );

  v_nova_quantidade := v_presente.quantidade_reservada + 1;
  v_novo_status := case
    when not v_presente.usa_cotas then 'reservado'
    when v_nova_quantidade >= v_presente.quantidade_total then 'reservado'
    else 'disponivel'
  end;

  update public.presentes p
     set quantidade_reservada = v_nova_quantidade,
         status = v_novo_status
   where p.id = p_presente_id
     and p.evento_id = p_evento_id;

  return query
  select p_presente_id, v_nova_quantidade, v_novo_status, v_presente.usa_cotas;
end;
$$;

create or replace function public.remover_reserva_presente(
  p_evento_id bigint,
  p_reserva_id bigint
)
returns table (
  presente_id bigint,
  quantidade_reservada integer,
  status text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reserva public.reservas_presentes%rowtype;
  v_presente public.presentes%rowtype;
  v_nova_quantidade integer;
  v_novo_status text;
begin
  select *
    into v_reserva
    from public.reservas_presentes r
   where r.id = p_reserva_id
     and r.evento_id = p_evento_id
   for update;

  if not found then
    raise exception 'Reserva não encontrada.';
  end if;

  select *
    into v_presente
    from public.presentes p
   where p.id = v_reserva.presente_id
     and p.evento_id = p_evento_id
   for update;

  if not found then
    raise exception 'Presente da reserva não encontrado.';
  end if;

  delete from public.reservas_presentes where id = v_reserva.id;

  v_nova_quantidade := greatest(v_presente.quantidade_reservada - 1, 0);
  v_novo_status := case
    when not v_presente.usa_cotas and v_nova_quantidade > 0 then 'reservado'
    else 'disponivel'
  end;

  update public.presentes p
     set quantidade_reservada = v_nova_quantidade,
         status = v_novo_status
   where p.id = v_presente.id;

  return query
  select v_presente.id, v_nova_quantidade, v_novo_status;
end;
$$;

revoke all on function public.reservar_presente(bigint, bigint, text) from public;
revoke all on function public.remover_reserva_presente(bigint, bigint) from public;
grant execute on function public.reservar_presente(bigint, bigint, text) to service_role;
grant execute on function public.remover_reserva_presente(bigint, bigint) to service_role;

-- Storage usado pelo painel V2.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'event-assets',
  'event-assets',
  true,
  20971520,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'video/mp4', 'video/webm']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- RLS: leitura pública somente do conteúdo do convite; escrita administrativa via API/service role.
alter table public.eventos enable row level security;
alter table public.configuracoes_evento enable row level security;
alter table public.confirmacoes enable row level security;
alter table public.presentes enable row level security;
alter table public.reservas_presentes enable row level security;
alter table public.galeria_evento enable row level security;
alter table public.historia_momentos enable row level security;

drop policy if exists "eventos_public_read" on public.eventos;
create policy "eventos_public_read" on public.eventos
for select using (ativo = true or auth.role() = 'authenticated');

drop policy if exists "configuracoes_public_read" on public.configuracoes_evento;
create policy "configuracoes_public_read" on public.configuracoes_evento
for select using (
  auth.role() = 'authenticated'
  or exists (
    select 1 from public.eventos e
    where e.id = configuracoes_evento.evento_id and e.ativo = true
  )
);

drop policy if exists "presentes_public_read" on public.presentes;
create policy "presentes_public_read" on public.presentes
for select using (
  auth.role() = 'authenticated'
  or exists (
    select 1 from public.eventos e
    where e.id = presentes.evento_id and e.ativo = true
  )
);

drop policy if exists "galeria_public_read" on public.galeria_evento;
create policy "galeria_public_read" on public.galeria_evento
for select using (
  auth.role() = 'authenticated'
  or exists (
    select 1 from public.eventos e
    where e.id = galeria_evento.evento_id and e.ativo = true
  )
);

drop policy if exists "historia_public_read" on public.historia_momentos;
create policy "historia_public_read" on public.historia_momentos
for select using (
  auth.role() = 'authenticated'
  or exists (
    select 1 from public.eventos e
    where e.id = historia_momentos.evento_id and e.ativo = true
  )
);

drop policy if exists "confirmacoes_admin_read" on public.confirmacoes;
create policy "confirmacoes_admin_read" on public.confirmacoes
for select to authenticated using (true);

drop policy if exists "reservas_admin_read" on public.reservas_presentes;
create policy "reservas_admin_read" on public.reservas_presentes
for select to authenticated using (true);

drop policy if exists "event_assets_public_read" on storage.objects;
create policy "event_assets_public_read" on storage.objects
for select using (bucket_id = 'event-assets');

commit;
